spring:
  datasource:
    username: stream
    password: stream
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://dockerrest_mysql_1:3306/stream?useSSL=false 
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding: 
      enabled: false
info:
  app:
    name: Stream String find vowel Application
    description: This application is prepared to find a first vowel after a vowel and a consonant
    version: 1.0.0
